'use client';

import { useEffect, useRef, useState } from 'react';
import { physicsDemoReadings } from '../historyDemoDocs';
import { physicsDomains, physicsEraLearning, physicsEras, physicsFrontierPaths, physicsLearningStages, physicsReferences } from '../physicsHistory';
import { DemoReadingPanel } from './DemoReadingPanel';

type DemoTrack = 'classical' | 'modern' | 'frontier';
type DemoId = 'measure' | 'fall' | 'orbit' | 'resonance' | 'heat' | 'gas' | 'field' | 'induction' | 'clock' | 'quantum' | 'atom' | 'decay' | 'matter' | 'chaos' | 'cosmos';
type Demo = { id: DemoId; track: DemoTrack; era: string; title: string; prompt: string; insight: string; challenge: string; control: string };

const demoTracks: { id: DemoTrack; title: string; subtitle: string }[] = [
  { id: 'classical', title: '经典世界', subtitle: '测量、运动、波与热' },
  { id: 'modern', title: '现代物理', subtitle: '统计、场、相对论与量子' },
  { id: 'frontier', title: '物质与前沿', subtitle: '原子核、材料、混沌与宇宙' },
];

const demos: Demo[] = [
  { id: 'measure', track: 'classical', era: 'MEASUREMENT · EVIDENCE', title: '测量：一组读数不是一个真值', prompt: '增大仪器噪声，观察同一加速度的重复读数如何分散；再看平均值为何仍有意义。', insight: '实验报告应给出不确定性和重复次数；“看起来接近”不是精确相等。', challenge: '这里只改变随机误差。若仪器整体偏高，重复再多也不能消除系统误差。', control: '测量噪声' },
  { id: 'fall', track: 'classical', era: 'GALILEO · MOTION', title: '落体：改变质量，不改变加速度', prompt: '拖动时间，比较两个不同质量的物体。忽略空气阻力时，它们会同时落地。', insight: '这是理想化模型的力量：先明确忽略什么，再检验留下的关系。', challenge: '试着说出加入空气阻力后，哪些新变量会改变结果。', control: '时间' },
  { id: 'orbit', track: 'classical', era: 'NEWTON · GRAVITY', title: '轨道：速度总在被引力折向', prompt: '改变轨道偏心率，观察同一引力中心如何让方向不断偏转。', insight: '“绕圈”并不表示没有力；速度方向持续改变，就意味着存在加速度。', challenge: '图中用均匀参数扫过椭圆，并不精确遵守开普勒第二定律；它强调几何关系。', control: '偏心率' },
  { id: 'resonance', track: 'classical', era: 'WAVES · NORMAL MODES', title: '驻波：边界选择允许的模式', prompt: '提高模态序号，数一数固定弦上的波腹与节点；两端始终不能移动。', insight: '连续弦可以振动，却不是任意形状都能稳定重复；边界条件筛选出离散的正常模。', challenge: '真实乐器的音色还来自多个模式的叠加、阻尼和共鸣箱。', control: '模态序号' },
  { id: 'heat', track: 'classical', era: 'THERMODYNAMICS · ENERGY', title: '热平衡：能量转移有方向', prompt: '推动热交换过程，观察等热容的两个物体如何趋向同一温度。', insight: '这个封闭、等热容模型中总能量不变；自发变化却把温差抹平。', challenge: '能量守恒没有单独给出热流方向；方向性需要热力学第二定律。', control: '热交换' },
  { id: 'gas', track: 'modern', era: 'STATISTICAL PHYSICS', title: '分子气体：温度是群体统计量', prompt: '升高温度，观察分子速度分布整体展宽，而不是每个分子都获得同一速度。', insight: '温度与大量微粒的平均动能有关；宏观稳定量可从剧烈波动的微观运动中涌现。', challenge: '这是定性二维模型，未精确采样 Maxwell–Boltzmann 分布，也没有模拟碰撞。', control: '温度' },
  { id: 'field', track: 'modern', era: 'FARADAY / MAXWELL', title: '电磁波：变化的场可以传播', prompt: '沿空间移动切片，观察相互垂直的 E 与 B 如何一起振荡。', insight: '光不是必须依赖介质的机械波；它是电磁场自身的传播解。', challenge: '线条是场分量的读图方式，不是空间里真实抖动的绳子。', control: '相位' },
  { id: 'induction', track: 'modern', era: 'FARADAY · INDUCTION', title: '电磁感应：变化的磁通产生电动势', prompt: '让磁体靠近和远离线圈；注意磁体瞬时停止时，线圈中的感应响应也减弱。', insight: '关键不是“附近有磁场”，而是穿过回路的磁通量随时间改变。', challenge: '楞次定律中的负号表示感应效应反抗磁通的变化，而不是能量凭空出现。', control: '磁体位置' },
  { id: 'clock', track: 'modern', era: 'EINSTEIN · RELATIVITY', title: '光钟：不变的光速带来时间膨胀', prompt: '提高相对速度，比较静止与运动光钟的一次来回路径。', insight: '不是钟“坏了”：不同世界线之间的固有时间确实不同。', challenge: '图比较的是惯性运动；加速、引力与广义相对论还需要新的几何。', control: 'v / c' },
  { id: 'quantum', track: 'modern', era: 'QUANTUM · AMPLITUDE', title: '双缝：先相加振幅，再得到概率', prompt: '移动相位，观察屏幕上明暗条纹如何平移；单个探测仍是离散的。', insight: '波纹是概率分布，不是“小球被切成两半”的轨迹照片。', challenge: '知道路径的信息会改变可干涉性；这不是观察者用眼睛“吓到”粒子。', control: '相位差' },
  { id: 'atom', track: 'frontier', era: 'ATOMIC SPECTRA', title: '原子光谱：能级差决定光子颜色', prompt: '选择不同跃迁，比较发射光子的能量；谱线只出现在特定位置。', insight: '原子能量不是连续滑尺，离散能级差对应离散光谱，这是量子理论的早期关键证据。', challenge: '这里使用氢原子简化能级；多电子原子还包含屏蔽、角动量与精细结构。', control: '跃迁能级' },
  { id: 'decay', track: 'frontier', era: 'NUCLEAR PHYSICS', title: '放射性衰变：个体随机，群体有规律', prompt: '推动半衰期时钟，观察样本中尚未衰变的原子核数量大致按指数规律减少。', insight: '理论不能预言某个原子核的确切衰变时刻，却能非常准确地预言大量样本的统计比例。', challenge: '有限样本会围绕理论曲线波动；样本越大，相对波动通常越小。', control: '经过半衰期' },
  { id: 'matter', track: 'frontier', era: 'CONDENSED MATTER', title: '能带：一个能隙改变材料行为', prompt: '调节能隙，比较固定能量的光子能否把电子从价带激发到导带。', insight: '材料性质不只由“含有哪些粒子”决定，也由大量原子形成的允许能态结构决定。', challenge: '真实吸收还受动量、缺陷、温度和选择定则影响；图只保留能量门槛。', control: '能隙' },
  { id: 'chaos', track: 'frontier', era: 'NONLINEAR DYNAMICS', title: '混沌：确定性不等于长期可预测', prompt: '推动时间，比较初始角只差 0.001 弧度的两套双摆轨迹如何逐渐分离。', insight: '方程完全确定，微小初值误差仍可被非线性放大；天气预测的困难不是“没有规律”。', challenge: '混沌不是纯随机；短期轨迹、统计特征和守恒结构仍可研究。', control: '演化时间' },
  { id: 'cosmos', track: 'frontier', era: 'COSMOLOGY · EVIDENCE', title: '宇宙膨胀：距离越远，退行越快', prompt: '推动时间滑块，让网格尺度变化；每个星系并非从某个中心“飞出”。', insight: '这是空间尺度因子改变的示意，不能据此画出宇宙的外部形状。', challenge: '宇宙学结论来自红移、微波背景、元素丰度等证据的联合，而不是这一张网格。', control: '尺度因子' },
];

const checks: Record<DemoId, { question: string; answers: string[]; correct: number; explain: string }> = {
  measure: { question: '若重复测量的散布变大，最合理的报告是什么？', answers: ['只保留最接近预期的一个数', '报告平均值、散布和测量条件', '宣布理论错误'], correct: 1, explain: '重复读数的平均与散布共同描述测量；还要说明仪器、环境和模型条件。' },
  fall: { question: '为什么这个实验中重物和轻物同步落下？', answers: ['重物其实没有受重力', '模型明确忽略空气阻力，重力加速度与质量无关', '质量在真空中都会相同'], correct: 1, explain: '这是理想化结论。加入空气阻力后，形状和面积会影响运动。' },
  orbit: { question: '轨道上速度方向不断变，为何不是“匀速直线运动”？', answers: ['速度只要大小不变就不变', '速度是向量，方向变化也意味着加速度', '引力只改变距离'], correct: 1, explain: '加速度描述速度向量的变化；向心效应正是方向持续改变。' },
  resonance: { question: '两端固定的弦为何只出现某些稳定模式？', answers: ['边界要求两端始终是节点', '弦上的点不能同时运动', '波速只能取整数'], correct: 0, explain: '只有能在弦长中容纳整数个半波长的形状同时满足两端固定。' },
  heat: { question: '在这个封闭模型中，热量自发从哪里流向哪里？', answers: ['从低温物体流向高温物体', '从高温物体流向低温物体', '两个物体都不改变'], correct: 1, explain: '能量守恒不等于每一过程都能倒放；温差会在自发热交换中减小。' },
  gas: { question: '升高气体温度，在微观图像中最合理的变化是？', answers: ['每个分子速度变得完全相同', '速度分布整体移向更高动能并变宽', '所有分子停止碰撞'], correct: 1, explain: '温度是统计量；同一温度下仍同时存在快分子和慢分子。' },
  field: { question: '这个示意真正想表达什么？', answers: ['电场和磁场是两种彼此无关的物质', '变化的电磁场可以在真空中传播', '所有光都只有一种颜色'], correct: 1, explain: '图中波形是简化读图。真实电磁场仍要由方程、边界条件和测量来判断。' },
  induction: { question: '什么时候线圈中的感应电动势最直接地出现？', answers: ['只要附近存在磁体', '穿过线圈的磁通量发生变化', '线圈温度足够高'], correct: 1, explain: 'Faraday 定律把感应电动势连接到磁通量的变化率。' },
  clock: { question: '运动光钟路径更长时，狭义相对论要求什么保持一致？', answers: ['光速 c', '每个观察者的坐标时间', '两条光路的几何长度'], correct: 0, explain: '在每个惯性系中光速相同；不同路径配合不同的时间间隔，导出时间膨胀。' },
  quantum: { question: '双缝屏幕上的条纹首先描述什么？', answers: ['每个粒子都沿着明暗波纹连续涂抹', '大量重复实验中各位置出现的概率', '仪器把粒子切成两半'], correct: 1, explain: '单次探测是离散事件；重复后统计分布呈现干涉。' },
  atom: { question: '原子发射光谱为何出现离散谱线？', answers: ['电子能量差只能取某些值', '棱镜自动删掉大多数颜色', '所有原子温度完全相同'], correct: 0, explain: '光子能量等于初末能级之差；能级离散使发射能量也离散。' },
  decay: { question: '“半衰期”能告诉我们什么？', answers: ['某个原子核必定在半衰期时刻衰变', '大量同类原子核经过一个半衰期约剩一半', '样本质量每秒线性减半'], correct: 1, explain: '半衰期是群体统计规律，不是个体倒计时。' },
  matter: { question: '在这个简化模型中，光子何时能跨越能隙？', answers: ['光子能量不小于能隙', '光子能量越小越容易', '只要材料里有电子'], correct: 0, explain: '能量守恒给出最低门槛；真实材料还要满足其他选择规则。' },
  chaos: { question: '混沌系统的核心含义更接近哪一项？', answers: ['方程没有规律', '确定性演化会放大微小初值差异', '任何时刻都完全不可预测'], correct: 1, explain: '混沌系统由确定方程演化，但长期预测范围受初值精度强烈限制。' },
  cosmos: { question: '这个网格图不应该被理解为？', answers: ['尺度因子随时间改变的示意', '宇宙从图中心炸进预先存在的空房间', '任意两点间距离可随尺度变化'], correct: 1, explain: '示意没有“宇宙外部”或特殊中心；它只表达共动距离随尺度因子变化。' },
};

export function PhysicsHistoryAtlas({ onOpenLesson }: { onOpenLesson: (lessonId: string) => void }) {
  const [activeEra, setActiveEra] = useState(0);
  const [track, setTrack] = useState<DemoTrack>('classical');
  const [demo, setDemo] = useState<DemoId>('measure');
  const [value, setValue] = useState(.45);
  const [playing, setPlaying] = useState(true);
  const [choice, setChoice] = useState<number | null>(null);
  const selectedDemo = demos.find(item => item.id === demo)!;
  const era = physicsEras[activeEra];
  const learning = physicsEraLearning[era.id];
  const visibleDemos = demos.filter(item => item.track === track);

  return <div className="physics-atlas">
    <section className="physics-hero">
      <div className="physics-kicker"><span>PHYSICS HISTORY · OBSERVATION → MODEL → TEST</span><i>高中起点 · 12 个阶段 · 15 个思想实验</i></div>
      <div className="physics-hero-grid"><div><h1>物理学不是<br /><em>结论年表</em></h1><p>它从测量开始：什么被观察到？什么模型能压缩这些观察？模型在哪里失效？沿着这条线，力学、场、相对论、量子与宇宙学成为一段连续但从不封闭的探索。</p></div><PhysicsMotif /></div>
      <div className="physics-progress-map">{physicsEras.map((item, index) => <button key={item.id} className={activeEra === index ? 'active' : ''} onClick={() => { setActiveEra(index); document.getElementById('physics-timeline')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }}><span>{String(index + 1).padStart(2, '0')}</span><b>{item.span}</b><small>{item.title}</small></button>)}</div>
    </section>

    <section className="physics-coverage-section">
      <div className="section-heading"><div><span>KNOWLEDGE COVERAGE</span><h2>不是一条名人年表，而是六张相连的知识网</h2></div><p>每个领域都从高中数学能抓住的量开始，向更深的模型延伸，并配有至少两个可操作现象。</p></div>
      <div className="physics-domain-grid">{physicsDomains.map((domain, index) => <article key={domain.title}><header><span>0{index + 1}</span><b>{domain.title}</b></header><p><small>高中起点</small>{domain.start}</p><p><small>继续延伸</small>{domain.expands}</p><div>{domain.labs.map(lab => <i key={lab}>{lab}</i>)}</div></article>)}</div>
    </section>

    <section className="physics-stage-section">
      <div className="section-heading"><div><span>LEARNING LADDER</span><h2>四级台阶，把“看懂动画”变成“会判断证据”</h2></div><p>可以按顺序学习，也可以先从感兴趣的现象进入，再回补卡片标出的先修知识。</p></div>
      <div className="physics-stage-grid">{physicsLearningStages.map(stage => <article key={stage.number}><span>{stage.number}</span><small>{stage.level}</small><h3>{stage.title}</h3><p>{stage.goal}</p><ul>{stage.checks.map(check => <li key={check}>{check}</li>)}</ul></article>)}</div>
    </section>

    <section className="physics-lab-section">
      <div className="section-heading"><div><span>PHENOMENON LAB</span><h2>先改变现象，再读模型</h2></div><p>图形不是“装饰动画”：每个实验都保留一个可控量，并在旁边指出它验证什么、又没有验证什么。</p></div>
      <PhysicsCanvas demo={demo} value={value} playing={playing} onValue={setValue} />
      <div className="physics-track-tabs" role="tablist" aria-label="互动实验学习阶段">{demoTracks.map(item => <button key={item.id} role="tab" aria-selected={item.id === track} className={item.id === track ? 'active' : ''} onClick={() => { const first = demos.find(candidate => candidate.track === item.id)!; setTrack(item.id); setDemo(first.id); setValue(.32); setChoice(null); }}><b>{item.title}</b><span>{item.subtitle}</span></button>)}</div>
      <div className="physics-demo-tabs" role="tablist" aria-label="物理史互动实验">{visibleDemos.map(item => <button key={item.id} role="tab" aria-selected={item.id === demo} className={item.id === demo ? 'active' : ''} onClick={() => { setDemo(item.id); setValue(item.id === 'clock' ? .25 : .32); setChoice(null); }}><span>{item.era}</span><b>{item.title}</b></button>)}</div>
      <div className="physics-player"><button onClick={() => setPlaying(current => !current)} aria-label={playing ? '暂停实验' : '播放实验'}>{playing ? 'Ⅱ' : '▶'}</button><label><span>{selectedDemo.control}</span><input aria-label={selectedDemo.control} type="range" min="0" max="1" step="0.001" value={value} onChange={event => { setPlaying(false); setValue(Number(event.target.value)); }} /></label><output>{demoOutput(demo, value)}</output></div>
      <div className="physics-lab-copy"><div><span>实验任务</span><p>{selectedDemo.prompt}</p></div><div><span>你应当观察到</span><p>{selectedDemo.insight}</p></div><div><span>模型边界</span><p>{selectedDemo.challenge}</p></div></div>
      <PhysicsCheck demo={demo} choice={choice} onChoose={setChoice} />
      <DemoReadingPanel reading={physicsDemoReadings[demo]} onOpenLesson={onOpenLesson} />
    </section>

    <section className="physics-timeline" id="physics-timeline">
      <div className="section-heading"><div><span>TWELVE TURNS IN PHYSICS</span><h2>十二次转向，每一步都留下可检验的痕迹</h2></div><p>用“证据、模型、边界”取代英雄式年表：科学理论不仅解释成功，也主动说明自己的适用范围。</p></div>
      <div className="physics-timeline-layout"><nav aria-label="物理学史时期">{physicsEras.map((item, index) => <button key={item.id} className={activeEra === index ? 'active' : ''} onClick={() => setActiveEra(index)}><i /><span>{item.span}</span><b>{item.title}</b></button>)}</nav><article className="physics-era-card" key={era.id}><header><span>{era.span}</span><i>第 {activeEra + 1} 站</i></header><p className="physics-question">“{era.question}”</p><h3>{era.title}</h3><div className="physics-era-learning"><div><span>难度</span><b>{learning.level}</b></div><div><span>先修</span><b>{learning.prerequisites}</b></div><div><span>学完能做到</span><b>{learning.outcome}</b></div></div><div className="evidence-stack"><section><span>OBSERVATION · 观测</span><p>{era.evidence}</p></section><section><span>MODEL · 模型</span><p>{era.model}</p></section><section><span>OPEN EDGE · 边界</span><p>{era.limit}</p></section></div><div className="physics-bridge"><span>连接到 GA / SPACE</span><p>{era.bridge}</p><button onClick={() => onOpenLesson(era.lessonId)}>进入对应课程 <i>→</i></button></div></article></div>
    </section>

    <section className="physics-frontier"><div><span>WHAT “FRONTIER” MEANS</span><h2>前沿不是更炫的名词，<br />而是更清楚的未知。</h2></div><ol><li><b>已成功</b><p>在已检验范围内，牛顿力学、Maxwell 理论、相对论、量子理论与标准模型各自极其有效。</p></li><li><b>尚未统一</b><p>量子理论与广义相对论的共同极限仍未被实验证实；“量子引力”是一组研究方向，不是一门已完成理论。</p></li><li><b>仍受观测约束</b><p>暗物质、暗能量、宇宙早期与中微子性质都要由数据筛选，不能只靠漂亮公式。</p></li></ol></section>

    <section className="physics-frontier-paths"><div className="section-heading"><div><span>FRONTIER PATHS</span><h2>六条从高中知识走到真实研究的问题链</h2></div><p>每条路线都分开写明起点、需要补的桥梁、已经取得的成功和仍然开放的问题。</p></div><div className="physics-frontier-grid">{physicsFrontierPaths.map((path, index) => <article key={path.title}><header><span>0{index + 1}</span><h3>{path.title}</h3></header><dl><div><dt>高中起点</dt><dd>{path.start}</dd></div><div><dt>概念桥梁</dt><dd>{path.bridge}</dd></div><div><dt>已经成功</dt><dd>{path.success}</dd></div><div><dt>仍然未知</dt><dd>{path.open}</dd></div></dl><button onClick={() => onOpenLesson(path.lessonId)}>进入数学桥梁 <i>→</i></button></article>)}</div></section>

    <section className="physics-reference-section"><div className="section-heading"><div><span>READ FURTHER</span><h2>从互动图回到可靠资料</h2></div><p>这些入口分别提供物理学史、相对论、粒子物理和宇宙学的进一步材料。</p></div><div className="reference-list">{physicsReferences.map((reference, index) => <a key={reference.url} href={reference.url} target="_blank" rel="noreferrer"><span>0{index + 1}</span><div><b>{reference.title}</b><p>{reference.note}</p></div><i>↗</i></a>)}</div></section>
  </div>;
}

function PhysicsMotif() { return <div className="physics-motif" aria-hidden="true"><i /><i /><i /><i /><span>measure</span><span>model</span><span>test</span><b>?</b></div>; }

function demoOutput(demo: DemoId, value: number) {
  if (demo === 'clock') return `${(value * .92).toFixed(2)} c`;
  if (demo === 'measure') return `±${(.05 + value * .7).toFixed(2)}`;
  if (demo === 'resonance') return `n = ${1 + Math.floor(value * 5)}`;
  if (demo === 'gas') return `${Math.round(100 + value * 700)} K`;
  if (demo === 'decay') return `${(value * 5).toFixed(1)} T½`;
  if (demo === 'matter') return `${(.4 + value * 2.8).toFixed(2)} eV`;
  return `${Math.round(value * 100)}%`;
}

function PhysicsCheck({ demo, choice, onChoose }: { demo: DemoId; choice: number | null; onChoose: (value: number) => void }) {
  const check = checks[demo];
  return <section className="physics-check" aria-label="理解检查"><div><span>先预测 · 再核对</span><h3>{check.question}</h3></div><div className="physics-check-options">{check.answers.map((answer, index) => <button key={answer} className={choice === index ? (index === check.correct ? 'correct' : 'incorrect') : ''} onClick={() => onChoose(index)}><i>{String.fromCharCode(65 + index)}</i>{answer}</button>)}</div>{choice !== null && <p className={choice === check.correct ? 'correct' : 'incorrect'}>{choice === check.correct ? '判断正确。' : '再看一次模型条件。'} {check.explain}</p>}</section>;
}

function PhysicsCanvas({ demo, value, playing, onValue }: { demo: DemoId; value: number; playing: boolean; onValue: (value: number) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const valueRef = useRef(value); const previousRef = useRef(0);
  useEffect(() => { valueRef.current = value; }, [value]);
  useEffect(() => { if (!playing) return; let frame = 0; const tick = (now: number) => { if (!previousRef.current) previousRef.current = now; const speed = demo === 'clock' ? .000055 : .000075; const next = (valueRef.current + Math.min(50, now - previousRef.current) * speed) % 1; previousRef.current = now; onValue(next); frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => { cancelAnimationFrame(frame); previousRef.current = 0; }; }, [demo, playing, onValue]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const rect = canvas.getBoundingClientRect(); const ratio = Math.min(devicePixelRatio, 2); canvas.width = Math.round(rect.width * ratio); canvas.height = Math.round(rect.height * ratio); const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); drawPhysics(ctx, rect.width, rect.height, demo, value); }, [demo, value]);
  return <div className="physics-canvas-wrap"><canvas ref={canvasRef} aria-label="物理现象互动图" /><div className="physics-canvas-label"><span>LIVE MODEL · NOT TO SCALE</span><b>{demos.find(item => item.id === demo)?.title}</b></div></div>;
}

function base(ctx: CanvasRenderingContext2D, w: number, h: number) { ctx.fillStyle = '#111820'; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = 'rgba(158,189,182,.08)'; ctx.lineWidth = 1; for (let x = 0; x < w; x += 32) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); } for (let y = 0; y < h; y += 32) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); } }
function dot(ctx: CanvasRenderingContext2D, x: number, y: number, color: string, radius = 5) { ctx.beginPath(); ctx.arc(x, y, radius, 0, Math.PI * 2); ctx.fillStyle = color; ctx.fill(); }
function line(ctx: CanvasRenderingContext2D, x1: number, y1: number, x2: number, y2: number, color: string, width = 1) { ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.strokeStyle = color; ctx.lineWidth = width; ctx.stroke(); }

function drawPhysics(ctx: CanvasRenderingContext2D, w: number, h: number, demo: DemoId, value: number) {
  base(ctx, w, h);
  if (demo === 'fall') drawFall(ctx, w, h, value);
  if (demo === 'heat') drawHeat(ctx, w, h, value);
  if (demo === 'measure') drawMeasure(ctx, w, h, value);
  if (demo === 'orbit') drawOrbit(ctx, w, h, value);
  if (demo === 'resonance') drawResonance(ctx, w, h, value);
  if (demo === 'gas') drawGas(ctx, w, h, value);
  if (demo === 'field') drawField(ctx, w, h, value);
  if (demo === 'induction') drawInduction(ctx, w, h, value);
  if (demo === 'clock') drawClock(ctx, w, h, value);
  if (demo === 'quantum') drawQuantum(ctx, w, h, value);
  if (demo === 'atom') drawAtom(ctx, w, h, value);
  if (demo === 'decay') drawDecay(ctx, w, h, value);
  if (demo === 'matter') drawMatter(ctx, w, h, value);
  if (demo === 'chaos') drawChaos(ctx, w, h, value);
  if (demo === 'cosmos') drawCosmos(ctx, w, h, value);
}

function label(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, color = '#9aaea8') { ctx.fillStyle = color; ctx.font = '10px ui-monospace, monospace'; ctx.fillText(text, x, y); }
function drawMeasure(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const center = h * .53, noise = .05 + t * .7, readings = Array.from({ length: 11 }, (_, index) => 9.8 + Math.sin(index * 2.37 + .4) * noise); const mean = readings.reduce((sum, reading) => sum + reading, 0) / readings.length, scale = w * .31; line(ctx, w * .19, center, w * .81, center, 'rgba(238,242,237,.42)'); [9, 9.5, 10, 10.5].forEach(reading => { const x = w * .5 + (reading - 9.8) * scale; line(ctx, x, center - 6, x, center + 6, '#71837c'); label(ctx, `${reading.toFixed(1)}`, x - 10, center + 26); }); readings.forEach((reading, index) => { const x = w * .5 + (reading - 9.8) * scale; dot(ctx, x, center - 32 - (index % 3) * 28, index % 2 ? '#55d8b0' : '#f0c15b', 5); line(ctx, x, center - 6, x, center - 20, 'rgba(102,218,181,.3)'); }); const mx = w * .5 + (mean - 9.8) * scale; line(ctx, mx, center - 125, mx, center + 10, '#eaf4ef', 2); label(ctx, `mean = ${mean.toFixed(2)} m/s²`, 36, 38, '#edf2ec'); label(ctx, `noise ≈ ±${noise.toFixed(2)} m/s² · 11 trials`, 36, 58, '#9fb4ab'); label(ctx, 'repeated readings', w * .19, h - 32); }
function drawFall(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const ground = h - 50, y = 48 + Math.min(1, t * 1.38) ** 2 * (ground - 64); line(ctx, 32, ground, w - 32, ground, '#6ed7b8', 2); dot(ctx, w * .37, y, '#f0c15b', 11); dot(ctx, w * .63, y, '#55d8b0', 6); label(ctx, 'heavy', w * .37 - 18, y - 21, '#f0c15b'); label(ctx, 'light', w * .63 - 15, y - 17, '#55d8b0'); label(ctx, `t = ${(t * 3.2).toFixed(2)} s · a = g`, 35, 36, '#edf2ec'); label(ctx, 'AIR RESISTANCE: OFF', 35, ground + 28); }
function drawOrbit(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const cx = w * .5, cy = h * .53, a = Math.min(w, h) * .28, e = .12 + t * .72, b = a * Math.sqrt(1 - e * e), focus = cx - a * e; ctx.strokeStyle = 'rgba(102,218,181,.52)'; ctx.lineWidth = 2; ctx.beginPath(); ctx.ellipse(cx, cy, a, b, 0, 0, Math.PI * 2); ctx.stroke(); const angle = t * Math.PI * 2; const x = cx + a * Math.cos(angle), y = cy + b * Math.sin(angle); dot(ctx, focus, cy, '#f2bd51', 12); dot(ctx, x, y, '#7be4c4', 7); line(ctx, x, y, focus, cy, 'rgba(242,189,81,.45)', 1); line(ctx, x, y, x - Math.sin(angle) * 38, y + Math.cos(angle) * 38, '#73d8ee', 2); label(ctx, `eccentricity e = ${e.toFixed(2)}`, 35, 38, '#edf2ec'); label(ctx, 'gravity →', focus + 18, cy - 18, '#f2bd51'); label(ctx, 'instantaneous velocity', x + 11, y + 23, '#73d8ee'); }
function drawResonance(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const mode = 1 + Math.floor(t * 5), left = 52, right = w - 52, mid = h * .55, phase = t * Math.PI * 2; line(ctx, left, mid, right, mid, 'rgba(238,242,237,.25)'); ctx.beginPath(); for (let step = 0; step <= 180; step++) { const u = step / 180, x = left + (right - left) * u, y = mid - Math.sin(mode * Math.PI * u) * Math.sin(phase) * h * .23; if (step === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y); } ctx.strokeStyle = '#55d8b0'; ctx.lineWidth = 3; ctx.stroke(); for (let node = 0; node <= mode; node++) { const x = left + (right - left) * node / mode; dot(ctx, x, mid, node === 0 || node === mode ? '#f0c15b' : '#ecf2ee', 4); } label(ctx, `normal mode n = ${mode} · λ = 2L/${mode}`, 36, 38, '#edf2ec'); label(ctx, `${mode - 1} internal node${mode === 2 ? '' : 's'} · ${mode} antinode${mode === 1 ? '' : 's'}`, 36, 57, '#9fb4ab'); label(ctx, 'fixed end', left - 22, mid + 31); label(ctx, 'fixed end', right - 22, mid + 31); }
function drawHeat(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const hot = 80 - 30 * t, cold = 20 + 30 * t, left = w * .27, right = w * .69, top = h * .28, height = h * .43, thermometer = (x: number, temperature: number, color: string, name: string) => { ctx.strokeStyle = '#bfcfca'; ctx.lineWidth = 2; ctx.strokeRect(x - 17, top, 34, height); const fill = height * (temperature - 10) / 80; ctx.fillStyle = color; ctx.fillRect(x - 13, top + height - fill, 26, fill); dot(ctx, x, top + height + 21, color, 12); label(ctx, `${name}: ${temperature.toFixed(0)} °C`, x - 42, top - 18, color); }; thermometer(left, hot, '#f0a653', 'hot'); thermometer(right, cold, '#54d9b2', 'cold'); for (let index = 0; index < 3; index++) { const x = left + 65 + index * 52 + Math.sin(t * Math.PI) * 22; line(ctx, x, h * .51, x + 22, h * .51, '#f0c15b', 2); } label(ctx, `T₁ + T₂ = ${(hot + cold).toFixed(0)} °C (equal heat capacities)`, 36, 38, '#edf2ec'); label(ctx, t < .98 ? 'temperature difference decreases' : 'thermal equilibrium', 36, h - 31, '#9fb4ab'); }
function drawGas(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const temperature = 100 + t * 700, speed = .35 + t * 1.2, left = 40, top = 75, width = w * .62, height = h - 125; ctx.strokeStyle = 'rgba(238,242,237,.5)'; ctx.strokeRect(left, top, width, height); const bins = [0, 0, 0, 0, 0]; for (let index = 0; index < 42; index++) { const factor = .38 + ((index * 37) % 17) / 13, x = left + 14 + ((index * 73 + t * 390 * speed * factor) % Math.max(20, width - 28)), y = top + 14 + ((index * 47 + Math.sin(index * 1.9 + t * 9) * 35 + height * 2) % Math.max(20, height - 28)), angle = index * 2.1 + t * 8, length = 4 + 11 * factor * speed; dot(ctx, x, y, index % 3 ? '#55d8b0' : '#f0c15b', 3); line(ctx, x, y, x + Math.cos(angle) * length, y + Math.sin(angle) * length, 'rgba(224,244,237,.65)'); bins[Math.min(4, Math.floor(factor * speed * 2.2))]++; } const chartLeft = w * .73, chartBottom = h - 62; line(ctx, chartLeft, 92, chartLeft, chartBottom, '#72867f'); line(ctx, chartLeft, chartBottom, w - 28, chartBottom, '#72867f'); bins.forEach((count, index) => { ctx.fillStyle = index < 2 ? '#55d8b0' : '#f0c15b'; ctx.fillRect(chartLeft + 9 + index * 17, chartBottom - count * 7, 11, count * 7); }); label(ctx, `T ≈ ${temperature.toFixed(0)} K · ⟨K⟩ ∝ T`, 36, 38, '#edf2ec'); label(ctx, 'speed distribution', chartLeft - 10, 75, '#9fb4ab'); label(ctx, 'slow → fast', chartLeft, chartBottom + 21); }
function drawField(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const mid = h * .54, phase = t * Math.PI * 2; line(ctx, 35, mid, w - 35, mid, 'rgba(245,241,229,.38)'); for (let x = 42; x < w - 36; x += 16) { const p = x / w * Math.PI * 4 + phase; const e = Math.sin(p) * h * .2, b = Math.sin(p) * h * .12; line(ctx, x, mid, x, mid - e, '#4be0ba', 2); line(ctx, x - 5, mid + b, x + 5, mid - b, '#9c8cf2', 1.5); } label(ctx, 'E field', 38, 34, '#4be0ba'); label(ctx, 'B field · symbolic out-of-page strokes', 38, 52, '#9c8cf2'); label(ctx, 'propagation →', w - 140, mid + 31, '#f0c15b'); }
function drawInduction(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const phase = t * Math.PI * 2, magnetX = w * .18 + (Math.sin(phase) + 1) * w * .17, coilX = w * .69, cy = h * .54, response = Math.cos(phase); ctx.fillStyle = '#cc5c57'; ctx.fillRect(magnetX - 38, cy - 25, 38, 50); ctx.fillStyle = '#6d8ed0'; ctx.fillRect(magnetX, cy - 25, 38, 50); label(ctx, 'N', magnetX - 24, cy + 4, '#fff'); label(ctx, 'S', magnetX + 14, cy + 4, '#fff'); for (let ring = 0; ring < 5; ring++) { ctx.beginPath(); ctx.ellipse(coilX + ring * 9, cy, 24, 78, 0, 0, Math.PI * 2); ctx.strokeStyle = '#f0c15b'; ctx.lineWidth = 2; ctx.stroke(); } const direction = response >= 0 ? 1 : -1, strength = Math.abs(response); line(ctx, coilX - 10, cy - 102, coilX + direction * (32 + strength * 42), cy - 102, `rgba(85,216,176,${.3 + strength * .7})`, 3); label(ctx, response >= 0 ? 'induced current →' : '← induced current', coilX - 58, cy - 118, '#55d8b0'); label(ctx, `ε ∝ −dΦ/dt · relative response ${strength.toFixed(2)}`, 36, 38, '#edf2ec'); label(ctx, Math.abs(response) < .12 ? 'turning point: flux changes slowly' : 'moving magnet: flux is changing', 36, h - 25, '#9fb4ab'); }
function drawClock(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const beta = t * .92, gamma = 1 / Math.sqrt(1 - beta * beta), top = 75, bottom = h - 62, left = w * .28, right = w * .68, shift = beta * (right - left) * .7; line(ctx, left, top, left, bottom, '#4ce0ba', 2); line(ctx, left, bottom, left, top, '#4ce0ba', 2); line(ctx, right, top, right + shift, bottom, '#f0c15b', 2); line(ctx, right + shift, bottom, right, top, '#f0c15b', 2); dot(ctx, left, top, '#4ce0ba', 5); dot(ctx, left, bottom, '#4ce0ba', 5); dot(ctx, right, top, '#f0c15b', 5); dot(ctx, right + shift, bottom, '#f0c15b', 5); label(ctx, 'rest clock', left - 33, top - 17, '#4ce0ba'); label(ctx, 'moving clock', right - 24, top - 17, '#f0c15b'); label(ctx, `γ = ${gamma.toFixed(2)}   Δt = γ Δτ`, 36, 37, '#edf2ec'); label(ctx, 'both light paths use c', w - 177, h - 24); }
function drawQuantum(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const barrier = w * .32, screen = w * .78, cy = h * .52, phase = t * Math.PI * 2; ctx.fillStyle = '#75827e'; ctx.fillRect(barrier - 3, 32, 6, h - 64); ctx.clearRect(barrier - 5, cy - 45, 10, 18); ctx.clearRect(barrier - 5, cy + 27, 10, 18); line(ctx, 46, cy, barrier - 10, cy, '#f0c15b', 2); for (let y = 42; y < h - 42; y += 2) { const a1 = Math.cos((y - cy) * .09 + phase), a2 = Math.cos((y - cy) * .09 - phase); const probability = (a1 + a2) ** 2 / 4; ctx.fillStyle = `rgba(79, 222, 184, ${.08 + probability * .9})`; ctx.fillRect(screen, y, 14, 2); } label(ctx, 'single detection →', 44, cy - 14, '#f0c15b'); label(ctx, 'two slits', barrier - 27, 24); label(ctx, 'probability on screen', screen - 48, 24, '#54d9b2'); label(ctx, 'amplitudes add · probabilities are measured', 36, h - 21, '#edf2ec'); }
function drawAtom(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const target = 2 + Math.floor(t * 4), left = w * .18, right = w * .7, bottom = h - 62, scale = h * .34, energyY = (n: number) => bottom - (1 - 1 / (n * n)) * scale; for (let n = 1; n <= 5; n++) { const y = energyY(n); line(ctx, left, y, right, y, n === target || n === 1 ? '#55d8b0' : 'rgba(205,220,214,.45)', n === target || n === 1 ? 2 : 1); label(ctx, `n=${n}  E=${(-13.6 / (n * n)).toFixed(2)} eV`, right + 12, y + 3, n === target ? '#f0c15b' : '#9fb4ab'); } const startY = energyY(target), endY = energyY(1), photon = 13.6 * (1 - 1 / (target * target)); line(ctx, w * .45, startY, w * .45, endY, '#f0c15b', 3); line(ctx, w * .45, endY, w * .45 - 7, endY + 13, '#f0c15b', 3); let previousX = w * .48; const previousY = (startY + endY) / 2; ctx.beginPath(); for (let step = 0; step <= 90; step++) { const x = w * .49 + step * w * .004, y = previousY + Math.sin(step * .8) * 7; if (step === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y); previousX = x; } ctx.strokeStyle = '#75c9f2'; ctx.lineWidth = 2; ctx.stroke(); dot(ctx, previousX, previousY, '#75c9f2', 2); label(ctx, `ΔE = hν = ${photon.toFixed(2)} eV`, 36, 38, '#edf2ec'); label(ctx, 'discrete energy levels → discrete spectral lines', 36, h - 23, '#9fb4ab'); }
function drawDecay(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const halfLives = t * 5, expected = 2 ** -halfLives, columns = 12, count = 96, left = 46, top = 83, spacingX = Math.min(31, (w * .58) / columns), spacingY = Math.min(30, (h - 130) / 8); let survivors = 0; for (let index = 0; index < count; index++) { const pseudo = ((index * 73 + 19) % 101) / 101, alive = pseudo < expected; if (alive) survivors++; const x = left + (index % columns) * spacingX, y = top + Math.floor(index / columns) * spacingY; dot(ctx, x, y, alive ? '#55d8b0' : 'rgba(116,132,126,.28)', alive ? 5 : 3); } const chartLeft = w * .7, chartBottom = h - 62, chartWidth = w * .24; line(ctx, chartLeft, 72, chartLeft, chartBottom, '#758780'); line(ctx, chartLeft, chartBottom, chartLeft + chartWidth, chartBottom, '#758780'); ctx.beginPath(); for (let step = 0; step <= 100; step++) { const u = step / 100, x = chartLeft + u * chartWidth, y = chartBottom - 2 ** (-u * 5) * (chartBottom - 86); if (step === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y); } ctx.strokeStyle = '#f0c15b'; ctx.lineWidth = 2; ctx.stroke(); dot(ctx, chartLeft + t * chartWidth, chartBottom - expected * (chartBottom - 86), '#edf2ec', 4); label(ctx, `t = ${halfLives.toFixed(1)} T½ · sample ${survivors}/${count}`, 36, 38, '#edf2ec'); label(ctx, 'N/N₀ = 2⁻ᵗ', chartLeft, 56, '#f0c15b'); label(ctx, 'individual random · ensemble predictable', 36, h - 23, '#9fb4ab'); }
function drawMatter(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const gap = .4 + t * 2.8, photon = 2, top = h * .2, bandHeight = h * .17, conductionY = top, gapPixels = 24 + gap * 25, valenceY = top + bandHeight + gapPixels, absorbed = photon >= gap; ctx.fillStyle = 'rgba(85,216,176,.18)'; ctx.fillRect(w * .23, conductionY, w * .54, bandHeight); ctx.fillStyle = 'rgba(156,140,242,.16)'; ctx.fillRect(w * .23, valenceY, w * .54, bandHeight); label(ctx, 'CONDUCTION BAND · mobile states', w * .25, conductionY + 22, '#55d8b0'); label(ctx, 'VALENCE BAND · filled states', w * .25, valenceY + bandHeight - 16, '#a899ef'); const electronX = w * .5; dot(ctx, electronX, valenceY + 22, '#f0c15b', 7); if (absorbed) { line(ctx, electronX, valenceY + 14, electronX, conductionY + bandHeight - 12, '#f0c15b', 3); dot(ctx, electronX, conductionY + bandHeight - 12, '#f0c15b', 7); } else { for (let step = 0; step < 5; step++) line(ctx, w * .11 + step * 15, valenceY + 22 + Math.sin(step) * 7, w * .12 + step * 15, valenceY + 22 - Math.sin(step) * 7, '#75c9f2', 2); } label(ctx, `band gap Eɢ = ${gap.toFixed(2)} eV · photon = ${photon.toFixed(2)} eV`, 36, 38, '#edf2ec'); label(ctx, absorbed ? 'photon absorbed: electron reaches conduction band' : 'photon below threshold: no excitation in this model', 36, h - 23, absorbed ? '#55d8b0' : '#75c9f2'); label(ctx, `${gapPixels.toFixed(0)} px represents ${gap.toFixed(2)} eV`, w - 240, valenceY - 15, '#9fb4ab'); }
type PendulumState = { a: number; b: number; av: number; bv: number };
function advancePendulum(state: PendulumState, dt: number) { const { a, b, av, bv } = state, delta = a - b, denominator = 2 - Math.cos(2 * delta), aa = (-9.81 * (2 * Math.sin(a) + Math.sin(a - 2 * b)) - 2 * Math.sin(delta) * (bv * bv + av * av * Math.cos(delta))) / denominator, ba = (2 * Math.sin(delta) * (2 * av * av + 2 * 9.81 * Math.cos(a) + bv * bv * Math.cos(delta))) / denominator; state.av += aa * dt; state.bv += ba * dt; state.a += state.av * dt; state.b += state.bv * dt; }
function drawChaos(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const originX = w * .5, originY = h * .2, length = Math.min(w, h) * .2, steps = Math.floor(40 + t * 720), first: PendulumState = { a: 1.55, b: 1.3, av: 0, bv: 0 }, second: PendulumState = { a: 1.55, b: 1.301, av: 0, bv: 0 }, trailA: [number, number][] = [], trailB: [number, number][] = []; for (let step = 0; step < steps; step++) { advancePendulum(first, .012); advancePendulum(second, .012); if (step % 5 === 0) { trailA.push([originX + length * Math.sin(first.a) + length * Math.sin(first.b), originY + length * Math.cos(first.a) + length * Math.cos(first.b)]); trailB.push([originX + length * Math.sin(second.a) + length * Math.sin(second.b), originY + length * Math.cos(second.a) + length * Math.cos(second.b)]); } } const drawTrail = (trail: [number, number][], color: string) => { ctx.beginPath(); trail.forEach(([x, y], index) => { if (index === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y); }); ctx.strokeStyle = color; ctx.lineWidth = 1.4; ctx.stroke(); }; drawTrail(trailA, 'rgba(85,216,176,.55)'); drawTrail(trailB, 'rgba(240,193,91,.5)'); const drawPendulum = (state: PendulumState, color: string) => { const x1 = originX + length * Math.sin(state.a), y1 = originY + length * Math.cos(state.a), x2 = x1 + length * Math.sin(state.b), y2 = y1 + length * Math.cos(state.b); line(ctx, originX, originY, x1, y1, color, 2); line(ctx, x1, y1, x2, y2, color, 2); dot(ctx, x1, y1, color, 5); dot(ctx, x2, y2, color, 7); return [x2, y2] as const; }; const endA = drawPendulum(first, '#55d8b0'), endB = drawPendulum(second, '#f0c15b'), separation = Math.hypot(endA[0] - endB[0], endA[1] - endB[1]) / length; label(ctx, `initial difference = 0.001 rad · current separation ≈ ${separation.toFixed(2)} L`, 36, 38, '#edf2ec'); label(ctx, 'same deterministic equations · nearby initial states', 36, h - 23, '#9fb4ab'); }
function drawCosmos(ctx: CanvasRenderingContext2D, w: number, h: number, t: number) { const scale = .4 + t * 1.5, cx = w / 2, cy = h / 2; ctx.save(); ctx.translate(cx, cy); for (let step = -4; step <= 4; step++) { line(ctx, step * 42 * scale, -h, step * 42 * scale, h, 'rgba(106,216,185,.26)'); line(ctx, -w, step * 42 * scale, w, step * 42 * scale, 'rgba(106,216,185,.26)'); } [[-2,-1],[1,-1],[-1,2],[2,1],[-2,2]].forEach(([x,y], i) => dot(ctx, x * 55 * scale, y * 45 * scale, i % 2 ? '#f0c15b' : '#5ce0ba', 4)); ctx.restore(); label(ctx, `scale factor a = ${scale.toFixed(2)}`, 36, 38, '#edf2ec'); label(ctx, 'comoving grid · no preferred center in this diagram', 36, h - 23); }
